# Generated by Django 6.0.6 on 2026-08-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workflowstatus',
            constraint=models.UniqueConstraint(fields=('workflow', 'order'), name='unique_workflow_order'),
        ),
    ]
